  release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: ME-Tools

      - name: Generate SHA256
        id: sha
        run: |
          sha256sum *.exe > sha256.checksum
          echo "build_sha=$(cat sha256.checksum)" >> $GITHUB_OUTPUT
          cat sha256.checksum

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ME-Tools [${{ needs.build.outputs.short_sha }}]
          tag_name: ${{ github.ref_name }}
          body: |
            **This release has been built by GitHub Actions**

            Commit:
            ```
            ${{ needs.build.outputs.full_sha }}
            ```

            Build SHA256:
            ```
            ${{ steps.sha.outputs.build_sha }}
            ```

            ## Information

            - Configuration: Release
            - Platform: x64
            - Compiler: MSVC
            - Automated build: GitHub Actions

            Source:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          files: |
            *.exe
            *.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
